[gravity]
domain = "gravity"
host = "0.0.0.0:32803"

[subscriber]
subscriber_id = "nats_exporter"
subscriber_name = "NATS Exporter"
state_store = "./statestore"
worker_count = 4
verbose = true
pipeline_start = 0
pipeline_end = -1

[rules]
subscription = "./settings/subscriptions.json"

[nats]
host = "0.0.0.0:32803"
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1
